# Default values for a crate deployment of 3 nodes.
# Chart consists of:
#   1) A Service (exposing the ports that crate uses)
#   2) A StatefulSet (initialising the cluster)
app: crate

image:
  name: crate
  tag: 3.3.5
  pullPolicy: IfNotPresent

# 1) The Service connecting 3 ports...
service:
  type: ClusterIP
  annotations: {}
  adminName: crate-web
  adminPort: 4200
  clusterName: cluster
  clusterPort: 4300
  postgresName: postgres
  postgresPort: 5432



## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

affinity: {}

tolerations: []
antiAffinity: "soft"
nodeAffinity: {}

crate:
  clusterName: quantumleap
  # https://crate.io/docs/crate/reference/en/latest/config/environment.html#use-max-50-of-available-ram
  createHeapSize: 3g
  recoverAfterTime: 5m
  replicas: 3
  recoverAfterNodes: 2
  # minimumMasterNodes is only required for Crate versions prior to 4 and will
  # be ignored when using a 4.x image.
  minimumMasterNodes: 2

http:
  cors:
    enabled: true
    allowOrigin: "*"

# 3) Resources
resources:
  requests:
    cpu: 300m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 5Gi

persistentVolume:
  enabled: true
  storageClass: retain
  accessModes:
    - ReadWriteOnce
  size: 20Gi  # Per instance
  annotations: {}

backupVolume:
  # even if set to true, it'll be ignored if persistentVolume.enabled is false,
  # since in that case the container gets an emptyDir volume for database file
  # storage.
  enabled: false
  storageClass: retain
  # accessModes gets hard-coded to ReadWriteMany since Crate backup requires a
  # volume shared by **all** nodes in the cluster.
  size: 100Gi  # must cater for data of **all** nodes
  annotations: {}

# Readiness probe
readinessProbe:
  enabled: false
  initialDelaySeconds: 60
  timeoutSeconds: 1
  failureThreshold: 3
  periodSeconds: 60
  successThreshold: 1

# Liveness probe
livenessProbe:
  enabled: false
  initialDelaySeconds: 240
  timeoutSeconds: 5
  failureThreshold: 5
  periodSeconds: 10
  successThreshold: 1

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
# 2) The StatefulSet forming the cluster...
